[2024-04-12T12:58:46.524+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T12:58:46.587+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eksplorasi.create_fruits_table manual__2024-04-12T12:55:56.795094+00:00 [queued]>
[2024-04-12T12:58:46.625+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eksplorasi.create_fruits_table manual__2024-04-12T12:55:56.795094+00:00 [queued]>
[2024-04-12T12:58:46.638+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-04-12T12:58:46.751+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2024-04-12 12:55:56.795094+00:00
[2024-04-12T12:58:46.795+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T12:58:46.810+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'eksplorasi', 'create_fruits_table', 'manual__2024-04-12T12:55:56.795094+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasi_dag.py', '--cfg-path', '/tmp/tmpblp7e667']
[2024-04-12T12:58:46.826+0000] {standard_task_runner.py:91} INFO - Job 178: Subtask create_fruits_table
[2024-04-12T12:58:46.825+0000] {standard_task_runner.py:63} INFO - Started process 1147 to run task
[2024-04-12T12:58:47.058+0000] {task_command.py:426} INFO - Running <TaskInstance: eksplorasi.create_fruits_table manual__2024-04-12T12:55:56.795094+00:00 [running]> on host 805e8d5936d1
[2024-04-12T12:58:47.308+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='eksplorasi' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T12:55:56.795094+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T12:55:56.795094+00:00'
[2024-04-12T12:58:47.311+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T12:58:47.312+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE fruits (
            id BIGSERIAL PRIMARY KEY,
            name VARCHAR(255),
            calories DECIMAL,
            fat DECIMAL,
            sugar DECIMAL,
            carbohydrates DECIMAL,
            protein DECIMAL
        );
        
[2024-04-12T12:58:47.339+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T12:58:47.371+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_db` isn't defined
[2024-04-12T12:58:47.396+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=eksplorasi, task_id=create_fruits_table, execution_date=20240412T125556, start_date=20240412T125846, end_date=20240412T125847
[2024-04-12T12:58:47.446+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 178 for task create_fruits_table (The conn_id `***_db` isn't defined; 1147)
[2024-04-12T12:58:47.516+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T12:58:47.545+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-04-12T12:58:47.546+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-12T12:58:47.610+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T12:58:47.636+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
