[2024-04-15T10:36:36.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T10:36:36.694+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2024-04-15T10:36:36.730+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2024-04-15T10:36:36.735+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T10:36:36.926+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2023-12-24 00:00:00+00:00
[2024-04-15T10:36:36.964+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T10:36:36.977+0000] {standard_task_runner.py:63} INFO - Started process 1114 to run task
[2024-04-15T10:36:36.978+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'eksplorasii_dag', 'create_fruits_table', 'scheduled__2023-12-24T00:00:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasii_dag.py', '--cfg-path', '/tmp/tmp656qdb0k']
[2024-04-15T10:36:37.029+0000] {standard_task_runner.py:91} INFO - Job 447: Subtask create_fruits_table
[2024-04-15T10:36:37.263+0000] {task_command.py:426} INFO - Running <TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2023-12-24T00:00:00+00:00 [running]> on host 2354a2c4893f
[2024-04-15T10:36:37.738+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='eksplorasii_dag' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-24T00:00:00+00:00'
[2024-04-15T10:36:37.748+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T10:36:37.749+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fruits (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            calories DECIMAL NOT NULL,
            fat DECIMAL NOT NULL,
            sugar DECIMAL NOT NULL,
            carbohydrates DECIMAL NOT NULL,
            protein DECIMAL NOT NULL
        );

        -- Perbaikan: Menambahkan sequence fruits_id_seq
        CREATE SEQUENCE IF NOT EXISTS fruits_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;
    
[2024-04-15T10:36:37.797+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T10:36:37.846+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `eksplorasi_postgres` isn't defined
[2024-04-15T10:36:37.863+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=eksplorasii_dag, task_id=create_fruits_table, execution_date=20231224T000000, start_date=20240415T103636, end_date=20240415T103637
[2024-04-15T10:36:37.944+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 447 for task create_fruits_table (The conn_id `eksplorasi_postgres` isn't defined; 1114)
[2024-04-15T10:36:37.979+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T10:36:37.998+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-15T10:36:38.028+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T10:36:38.043+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
