[2024-04-15T10:04:56.126+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T10:04:56.190+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2023-04-01T00:00:00+00:00 [queued]>
[2024-04-15T10:04:56.226+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2023-04-01T00:00:00+00:00 [queued]>
[2024-04-15T10:04:56.231+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T10:04:56.296+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2023-04-01 00:00:00+00:00
[2024-04-15T10:04:56.341+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=279) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T10:04:56.343+0000] {standard_task_runner.py:63} INFO - Started process 299 to run task
[2024-04-15T10:04:56.418+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'eksplorasii_dag', 'create_fruits_table', 'scheduled__2023-04-01T00:00:00+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasii_dag.py', '--cfg-path', '/tmp/tmpq2z3_o5y']
[2024-04-15T10:04:56.435+0000] {standard_task_runner.py:91} INFO - Job 308: Subtask create_fruits_table
[2024-04-15T10:04:56.781+0000] {task_command.py:426} INFO - Running <TaskInstance: eksplorasii_dag.create_fruits_table scheduled__2023-04-01T00:00:00+00:00 [running]> on host 2354a2c4893f
[2024-04-15T10:04:57.280+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='eksplorasii_dag' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-01T00:00:00+00:00'
[2024-04-15T10:04:57.283+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T10:04:57.284+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fruits (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            calories DECIMAL NOT NULL,
            fat DECIMAL NOT NULL,
            sugar DECIMAL NOT NULL,
            carbohydrates DECIMAL NOT NULL,
            protein DECIMAL NOT NULL
        );

        -- Perbaikan: Menambahkan sequence fruits_id_seq
        CREATE SEQUENCE IF NOT EXISTS fruits_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;
    
[2024-04-15T10:04:57.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T10:04:57.323+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `eksplorasi_postgres` isn't defined
[2024-04-15T10:04:57.351+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=eksplorasii_dag, task_id=create_fruits_table, execution_date=20230401T000000, start_date=20240415T100456, end_date=20240415T100457
[2024-04-15T10:04:57.431+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 308 for task create_fruits_table (The conn_id `eksplorasi_postgres` isn't defined; 299)
[2024-04-15T10:04:57.496+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T10:04:57.513+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-15T10:04:57.597+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T10:04:57.642+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
