[2024-04-12T11:48:13.431+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T11:48:13.705+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas2.write_to_csv manual__2024-04-12T11:43:54.463606+00:00 [queued]>
[2024-04-12T11:48:13.733+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas2.write_to_csv manual__2024-04-12T11:43:54.463606+00:00 [queued]>
[2024-04-12T11:48:13.734+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 6
[2024-04-12T11:48:13.816+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-04-12 11:43:54.463606+00:00
[2024-04-12T11:48:13.851+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=404) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T11:48:13.858+0000] {standard_task_runner.py:63} INFO - Started process 415 to run task
[2024-04-12T11:48:13.866+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas2', 'write_to_csv', 'manual__2024-04-12T11:43:54.463606+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/prioritas2_dag.py', '--cfg-path', '/tmp/tmp61iomvtp']
[2024-04-12T11:48:13.868+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask write_to_csv
[2024-04-12T11:48:14.065+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas2.write_to_csv manual__2024-04-12T11:43:54.463606+00:00 [running]> on host 805e8d5936d1
[2024-04-12T11:48:14.427+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas2' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T11:43:54.463606+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T11:43:54.463606+00:00'
[2024-04-12T11:48:14.429+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T11:48:14.432+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T11:48:14.433+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: write_to_csv() missing 1 required positional argument: 'data'
[2024-04-12T11:48:14.463+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas2, task_id=write_to_csv, execution_date=20240412T114354, start_date=20240412T114813, end_date=20240412T114814
[2024-04-12T11:48:14.512+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task write_to_csv (write_to_csv() missing 1 required positional argument: 'data'; 415)
[2024-04-12T11:48:14.549+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T11:48:14.609+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T11:48:14.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
