[2024-04-13T15:58:32.783+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-13T15:58:32.802+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eksplorasi.create_fruits_table scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-13T15:58:32.812+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eksplorasi.create_fruits_table scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-13T15:58:32.812+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 6
[2024-04-13T15:58:32.831+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2024-04-12 00:00:00+00:00
[2024-04-13T15:58:32.839+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-13T15:58:32.841+0000] {standard_task_runner.py:63} INFO - Started process 266 to run task
[2024-04-13T15:58:32.841+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'eksplorasi', 'create_fruits_table', 'scheduled__2024-04-12T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasi_dag.py', '--cfg-path', '/tmp/tmpnv165s20']
[2024-04-13T15:58:32.844+0000] {standard_task_runner.py:91} INFO - Job 219: Subtask create_fruits_table
[2024-04-13T15:58:32.911+0000] {task_command.py:426} INFO - Running <TaskInstance: eksplorasi.create_fruits_table scheduled__2024-04-12T00:00:00+00:00 [running]> on host a8c8062a752a
[2024-04-13T15:58:33.005+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='eksplorasi' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-12T00:00:00+00:00'
[2024-04-13T15:58:33.007+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-13T15:58:33.008+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE fruits (
            id BIGSERIAL PRIMARY KEY,
            name VARCHAR(255),
            calories DECIMAL,
            fat DECIMAL,
            sugar DECIMAL,
            carbohydrates DECIMAL,
            protein DECIMAL
        );
        
[2024-04-13T15:58:33.016+0000] {base.py:84} INFO - Using connection ID 'my_postgres' for task execution.
[2024-04-13T15:58:33.025+0000] {base.py:84} INFO - Using connection ID 'my_postgres' for task execution.
[2024-04-13T15:58:33.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-13T15:58:33.029+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.29.0.2), port 5432 failed: fe_sendauth: no password supplied

[2024-04-13T15:58:33.038+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=eksplorasi, task_id=create_fruits_table, execution_date=20240412T000000, start_date=20240413T155832, end_date=20240413T155833
[2024-04-13T15:58:33.054+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 219 for task create_fruits_table (connection to server at "postgres" (172.29.0.2), port 5432 failed: fe_sendauth: no password supplied
; 266)
[2024-04-13T15:58:33.096+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-13T15:58:33.113+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-04-13T15:58:33.115+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-13T15:58:33.130+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-13T15:58:33.141+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
