[2024-04-15T16:26:50.566+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T16:26:50.607+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas_2.write_to_csv scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T16:26:50.627+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas_2.write_to_csv scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T16:26:50.628+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-04-15T16:26:50.650+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-04-14 00:00:00+00:00
[2024-04-15T16:26:50.665+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=822) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T16:26:50.671+0000] {standard_task_runner.py:63} INFO - Started process 825 to run task
[2024-04-15T16:26:50.674+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas_2', 'write_to_csv', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/prioritas2_dag.py', '--cfg-path', '/tmp/tmppurd09w_']
[2024-04-15T16:26:50.676+0000] {standard_task_runner.py:91} INFO - Job 522: Subtask write_to_csv
[2024-04-15T16:26:50.751+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas_2.write_to_csv scheduled__2024-04-14T00:00:00+00:00 [running]> on host 0c479e6c33e4
[2024-04-15T16:26:50.850+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas_2' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T16:26:50.853+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T16:26:50.864+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T16:26:50.865+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/prioritas2_dag.py", line 20, in write_to_csv
    with open(file_path, 'w', newline='') as csv_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dags/data/output/products.csv'
[2024-04-15T16:26:50.883+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas_2, task_id=write_to_csv, execution_date=20240414T000000, start_date=20240415T162650, end_date=20240415T162650
[2024-04-15T16:26:50.908+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 522 for task write_to_csv ([Errno 2] No such file or directory: 'dags/data/output/products.csv'; 825)
[2024-04-15T16:26:50.927+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T16:26:50.954+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T16:26:50.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
